# Generated by Django 2.2.7 on 2019-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
