# Generated by Django 2.2.7 on 2019-11-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_is_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_moderation',
            field=models.NullBooleanField(default=False),
        ),
    ]
