# Generated by Django 2.2.7 on 2019-11-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191129_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_moderation',
        ),
    ]
