# Generated by Django 2.2.7 on 2019-11-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_post_is_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_moderation',
            field=models.NullBooleanField(default=False),
        ),
    ]
