# Generated by Django 2.2.8 on 2019-12-10 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20191208_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True),
        ),
    ]
